// COMMON
export const CLEAN_STATE = 'CLEAN_STATE';
export const SET_RECALCULATE_LAYOUT_SCROLL = 'SET_RECALCULATE_LAYOUT_SCROLL';
export const SUCCESS_RECALCULATE_LAYOUT_SCROLL =
  'SUCCESS_RECALCULATE_LAYOUT_SCROLL';

// API
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'show_message';
export const HIDE_MESSAGE = 'hide_message';
export const TOGGLE_APP_DRAWER = 'toggle_app_drawer';
export const UPDATING_CONTENT = 'updating_content';

//APP SETTING
export const TOGGLE_NAV_COLLAPSED = 'TOGGLE_NAV_COLLAPSED';
export const SET_INITIAL_PATH = 'SET_INITIAL_PATH';
export const SET_NAVIGATE_AFTER_INTERMEDIA = 'SET_NAVIGATE_AFTER_INTERMEDIA';

// AUTH
export const LOGOUT = 'LOGOUT';
export const SET_LOGIN_REDIRECT_TO = 'SET_LOGIN_REDIRECT_TO';
export const INCREASE_LOGIN_ATTEMPT = 'INCREASE_LOGIN_ATTEMPT';
export const RESET_LOGIN_ATTEMPT = 'RESET_LOGIN_ATTEMPT';
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';
export const WIPE_USER = 'WIPE_USER';
export const RESET_TEMPT = 'RESET_TEMPT';
export const OTP_RESET_TIMEOUT = 'OTP_RESET_TIMEOUT';
export const SIGN_IN_SSO_SUCCESS = 'SIGN_IN_SSO_SUCCESS';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const SET_CODE_VERIFIER = 'SET_CODE_VERIFIER';


// PROFILE
export const GET_PROFILE_DETAIL_REQUEST = 'GET_PROFILE_DETAIL_REQUEST';
export const GET_PROFILE_DETAIL_SUCCESS = 'GET_PROFILE_DETAIL_SUCCESS';
export const GET_PROFILE_DETAIL_ERROR = 'GET_PROFILE_DETAIL_ERROR';
export const UPDATE_PROFILE_DETAIL = 'UPDATE_PROFILE_DETAIL';


// VIEW
export const SET_VIEW_HEIGHT = 'SET_VIEW_HEIGHT';

// USER APPLICATION
export const GET_MANAGABLE_APPLICATION_REQUEST =
  'GET_MANAGABLE_APPLICATION_REQUEST';
export const GET_MANAGABLE_APPLICATION_SUCCESS =
  'GET_MANAGABLE_APPLICATION_SUCCESS';
export const GET_MANAGABLE_APPLICATION_ERROR =
  'GET_MANAGABLE_APPLICATION_ERROR';
export const SELECT_APP = 'SELECT_APP';
export const SET_EXCLUSIVE_NAV_ID = 'SET_EXCLUSIVE_NAV_ID';
export const SET_NAV_PARAM = 'SET_NAV_PARAM';

// SSO
export const DISPATCH_SUCESS = 'DISPATCH_SUCESS';
export const DISPATCH_ERROR = 'DISPATCH_ERROR';
export const TOGGLE_SSO_SUCCESS = 'TOGGLE_SSO_SUCCESS';
export const TOGGLE_SSO_ERROR = 'TOGGLE_SSO_ERROR';
export const SSO_AUTH_CODE_REQUEST = 'SSO_AUTH_CODE_REQUEST';
export const SSO_AUTH_CODE_SUCCESS = 'SSO_AUTH_CODE_SUCCESS';
export const SSO_AUTH_CODE_ERROR = 'SSO_AUTH_CODE_ERROR';